eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: subject
  application:
    name: eureka-client-subject
words: I,You,He,She,It
server:
  port: 8014
  
---
spring:
  profiles: verb
  application:
    name: eureka-client-verb
words: ran,knew,had,saw,bought
server:
  port: 8015

---
spring:
  profiles: article
  application:
    name: eureka-client-article
words: a,the
server:
  port: 8016

---
spring:
  profiles: adjective
  application:
    name: eureka-client-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8017

---
spring:
  profiles: noun
  application:
    name: eureka-client-noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 8018

---
spring:
  profiles: noun2
  application:
    name: eureka-client-noun
words: noun2
server:
  port: 8019
